name: guitar_wings
description: A Guitar Tuition App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/


dependencies:

  flutter_fft: ^1.0.1

  flutter:
    sdk: flutter

cupertino_icons: ^0.1.3




dev_dependencies:
  flutter_test:
    sdk: flutter


